### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Quafadas** [tarao/record4s#45]
Hi, 

I have a couple of questions - this would be a discussion rather than an issue... but didn't see discussions on the repo. 

1. Is there an obvious way to convert records into a scala JS,  js.Object, js.Literal or similar? i.e. for interop with native JS libs? 
2. Would you consider merging an attempt at `ujson` integration? 
3. Would it be expected to play nicely with structural types?

This compiles, but throws at runtime. 

```
import com.github.tarao.record4s.%
import reflect.Selectable.reflectiveSelectable

@main def playdoh =

  type BarPlottable = {
    val x: Int
    val y: Int
    val label: String
  }

  val t = %(x = 1, y = 2, label = "String")

  def typeTest(r: BarPlottable) =
    println(r.x)
    r.y
    r.label

  typeTest(t)

```
Compiles, but throws at runtime. 

Full disclosure : My interest in your project, is that these sorts of records look dynamic enough to easily constructible from existing data, but static enough to provide the safety guarantees, that would helpful for my pet charting project.

**Comment by tarao** [comment]
Great! PRs are welcome.  I will give follow-up commits if I find any design concerns.  So, feel free to make a PR!

**Comment by Quafadas** [comment]
Well... I made a start in #46 , but my "parrot circe" hope died quite quickly, and I've realised that I'm way out of my depth! I'll put out a couple of feelers to see if I'm going in the right sort of direction at least...

**Comment by Quafadas** [comment]
I'm going to close this, as I think these two merges have answered my questions in fine style. 

Here was my use case... 
![image](https://github.com/tarao/record4s/assets/24899792/0dd5ba90-f32c-4e01-b1dd-0d61fc7ad41a)

And I'm very excited, that it worked! This is a really cool project - thank you for the time you've spent on it!
